### ISSUE TITLE
Documentação + unidadeEleitoral

### ISSUE THREAD

**Issue by gabrielacaesar** [augusto-herrmann/divulgacandcontas-doc#3]
Oi, @augusto-herrmann! Tudo bem?

Estava consultando a documentação não oficial da API para tentar baixar os PDFs de certidão criminal dos candidatos de 2018 e 2020 e também ganhar mais experiência com a API do TSE.

Não consegui descobrir como coletar os números da ``unidadeEleitoral`` para fazer requisições para todos os municípios. Há algum lugar onde eu consiga esse ID? Chequei no arquivo de candidatos do repositório de dados do TSE, mas os números da UE que constam lá não bateram.

Também há alguma forma de conseguir o ``id`` de todos os candidatos?

Por fim, eu gostaria de saber se você está em contato com o TSE e se há previsão de eles terem uma API documentada. Eu já registrei essa demanda na Ouvidoria do TSE.

Muito obrigada pela ajuda!

**Comment by augusto-herrmann** [comment]
Olá, @gabrielacaesar! Tudo bem, e com você?

Você chegou a olhar o [script](https://github.com/augusto-herrmann/eleicoes-2020-planos-de-governo/tree/main/scripts/divulgacandcontas) que a @anapaulagomes e eu fizemos para baixar os planos de governo? Alguns exemplos de uso da API estão lá.

Não cheguei a examinar esses dados sobre certidões criminais. Também ainda não procurei a `unidadeEleitoral`. Quando tiver um tempo para brincar com essa API novamente, posso tentar achar.

> Também há alguma forma de conseguir o id de todos os candidatos?

Creio que [esta chamada](https://github.com/augusto-herrmann/eleicoes-2020-planos-de-governo/blob/main/scripts/divulgacandcontas/mayor_proposals.py#L113) deva te retornar algumas informações sobre os candidatos às eleições municipais de 2020, incluindo os `id`s.

> Por fim, eu gostaria de saber se você está em contato com o TSE e se há previsão de eles terem uma API documentada. Eu já registrei essa demanda na Ouvidoria do TSE.

Sim, tem uma pessoa do TSE que é associado da Open Knowledge Brasil e havia revelado que estava sendo preparado um Plano de Dados Abertos do TSE. Mas não continuei acompanhando o assunto desde então. Eu cheguei a revelar essa demanda pela documentação da API e a existência dessa documentação não oficial que fizemos em 2020.
